name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Force reinstall latest Docker
        run: |
          # Удаляем старые версии Docker
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          # Устанавливаем зависимости
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          # Добавляем официальный GPG-ключ Docker
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          # Добавляем репозиторий Docker
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          # Устанавливаем Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
          # Проверяем версию Docker
          docker version

      - name: Install and start Selenoid
        run: |
          curl -s https://aerokube.com/cm/bash | bash
          ./cm selenoid start --vnc --last-versions 1
          sleep 5
          curl http://localhost:4444/status

      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
        continue-on-error: true

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true